export default [
    {
        id: 1,
        name: 'GitHub Profile',
        url: 'https://github.com/lorisleiva',
        frequency: '0 22 * * *',
        frequency_for_humans: 'Every day at 10pm',
        next_shot_in: '19 hours',
        device_for_humans: 'Screen 1024x768 (full page)',
        device: 'Screen',
        width: 1024,
        height: 768,
        fullpage: true,
        css: '.introduction-banner { display: none; }',
        created_ago: '2 months ago',
        shots: [
            {
                id: 6,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768 (full page)',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: true,
                css: '.introduction-banner { display: none; }',
                created_at: 'May 29th 2019 at 10:00pm',
                created_ago: '5 minutes ago',
                image: '/img/stubs/p1-6.png',
            },
            {
                id: 5,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768 (full page)',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: true,
                css: '.introduction-banner { display: none; }',
                created_at: 'May 28th 2019 at 10:00pm',
                created_ago: '1 day ago',
                image: '/img/stubs/p1-5.png',
            },
            {
                id: 4,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                css: '.introduction-banner { display: none; }',
                created_at: 'May 27th 2019 at 10:00pm',
                created_ago: '2 days ago',
                image: '/img/stubs/p1-4.png',
            },
            {
                id: 3,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                css: '.introduction-banner { display: none; }',
                created_at: 'May 26th 2019 at 10:00pm',
                created_ago: '3 days ago',
                image: '/img/stubs/p1-3.png',
            },
            {
                id: 2,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'May 25th 2019 at 10:00pm',
                created_ago: '4 days ago',
                image: '/img/stubs/p1-2.png',
            },
            {
                id: 1,
                name: 'GitHub Profile',
                url: 'https://github.com/lorisleiva',
                frequency: '0 22 * * *',
                frequency_for_humans: 'Every day at 10pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'May 24th 2019 at 10:00pm',
                created_ago: '5 days ago',
                image: '/img/stubs/p1-1.png',
            },
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 2,
        name: 'Packagist statistics',
        url: 'https://packagist.org/packages/lorisleiva/laravel-deployer/stats',
        frequency: '0 9 * * *',
        frequency_for_humans: 'Every day at 9am',
        next_shot_in: '19 hours',
        device: 'Screen 1024x768',
        created_ago: '5 months ago',
        shots: [
            {
                id: 1,
                name: 'Packagist statistics',
                url: 'https://packagist.org/packages/lorisleiva/laravel-deployer/stats',
                frequency: '0 9 * * *',
                frequency_for_humans: 'Every day at 9am',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'June 25th 2019 at 10:00pm',
                created_ago: '7 hours ago',
                image: '/img/stubs/p2.png',
            }
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 3,
        name: 'Youtube channel',
        url: 'https://www.youtube.com/channel/UCUO1du7KyhmCmjVIONIcq9A?view_as=subscriber',
        frequency: '0 16 * * 1',
        frequency_for_humans: 'Every Monday at 4pm',
        next_shot_in: '19 hours',
        device: 'Screen 1024x768',
        created_ago: '5 months ago',
        shots: [
            {
                id: 1,
                name: 'Youtube channel',
                url: 'https://www.youtube.com/channel/UCUO1du7KyhmCmjVIONIcq9A?view_as=subscriber',
                frequency: '0 16 * * 1',
                frequency_for_humans: 'Every Monday at 4pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'June 25th 2019 at 10:00pm',
                created_ago: '3 days ago',
                image: '/img/stubs/p3.png',
            }
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 4,
        name: 'Laravel vs Ruby on Rails',
        url: 'https://trends.google.com/trends/explore?date=all&q=Laravel,Ruby%20on%20rails',
        frequency: '0 0 1 1 *',
        frequency_for_humans: 'Every year on January 1st',
        next_shot_in: '19 hours',
        device: 'Screen 1024x768',
        created_ago: '6 months ago',
        shots: [
            {
                id: 1,
                name: 'Laravel vs Ruby on Rails',
                url: 'https://trends.google.com/trends/explore?date=all&q=Laravel,Ruby%20on%20rails',
                frequency: '0 0 1 1 *',
                frequency_for_humans: 'Every year on January 1st',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'June 25th 2019 at 10:00pm',
                created_ago: '5 months ago',
                image: '/img/stubs/p4.png',
            }
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 5,
        name: 'Blog evolution',
        url: 'https://lorisleiva.com',
        frequency: '0 0 1 * *',
        frequency_for_humans: 'The 1st of each month',
        next_shot_in: '19 hours',
        device: 'Screen 1024x768',
        created_ago: '1 year ago',
        shots: [
            {
                id: 1,
                name: 'Blog evolution',
                url: 'https://lorisleiva.com',
                frequency: '0 0 1 * *',
                frequency_for_humans: 'The 1st of each month',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'June 25th 2019 at 10:00pm',
                created_ago: '2 weeks ago',
                image: '/img/stubs/p5.png',
            }
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 6,
        name: 'Twitter profile',
        url: 'https://twitter.com/lorismatic',
        frequency: '0 16 * * 1',
        frequency_for_humans: 'Every Monday at 4pm',
        next_shot_in: '19 hours',
        device_for_humans: 'Screen 1024x768',
        device: 'Screen',
        width: 1024,
        height: 768,
        fullpage: false,
        created_ago: '1 year ago',
        shots: [
            {
                id: 1,
                name: 'Twitter profile',
                url: 'https://twitter.com/lorismatic',
                frequency: '0 16 * * 1',
                frequency_for_humans: 'Every Monday at 4pm',
                device_for_humans: 'Screen 1024x768',
                device: 'Screen',
                width: 1024,
                height: 768,
                fullpage: false,
                created_at: 'June 25th 2019 at 10:00pm',
                created_ago: '18 hours ago',
                image: '/img/stubs/p6.png',
            }
        ],
        get latest_shot () { return this.shots[0] },
        get shot_count () { return this.shots.length },
    },
    {
        id: 7,
        name: 'Stripe dashboard',
        url: 'https://dashboard.stripe.com/test/dashboard',
        frequency: '0 0 1 * *',
        frequency_for_humans: 'The 1st of each month',
        next_shot_in: '19 hours',
        device_for_humans: 'Screen 1024x768',
        device: 'Screen',
        width: 1024,
        height: 768,
        fullpage: false,
        created_ago: '1 year ago',
        shots: [],
        get latest_shot () { return this.shots[0] || null },
        get shot_count () { return this.shots.length },
    },
]
