export const frequencyOptions = [
    { value: 'yearly', name: 'Once a year' },
    { value: 'monthly', name: 'Once a month' },
    { value: 'weekly', name: 'Once a week' },
    { value: 'daily', name: 'Once a day' },
    { value: 'hourly', name: 'Once an hour' },
    { value: 'custom', name: 'Custom' },
]

export const monthOptions = [
    { value: 1, name: 'January' },
    { value: 2, name: 'February' },
    { value: 3, name: 'March' },
    { value: 4, name: 'April' },
    { value: 5, name: 'May' },
    { value: 6, name: 'June' },
    { value: 7, name: 'July' },
    { value: 8, name: 'August' },
    { value: 9, name: 'September' },
    { value: 10, name: 'October' },
    { value: 11, name: 'November' },
    { value: 12, name: 'December' },
]

export const weekOptions = [
    { value: 1, name: 'Monday' },
    { value: 2, name: 'Tuesday' },
    { value: 3, name: 'Wednesday' },
    { value: 4, name: 'Thursday' },
    { value: 5, name: 'Friday' },
    { value: 6, name: 'Saturday' },
    { value: 0, name: 'Sunday' },
]

export const dayOptions = [
    { value: 1, name: '1st' },
    { value: 2, name: '2nd' },
    { value: 3, name: '3rd' },
    { value: 4, name: '4th' },
    { value: 5, name: '5th' },
    { value: 6, name: '6th' },
    { value: 7, name: '7th' },
    { value: 8, name: '8th' },
    { value: 9, name: '9th' },
    { value: 10, name: '10th' },
    { value: 11, name: '11th' },
    { value: 12, name: '12th' },
    { value: 13, name: '13th' },
    { value: 14, name: '14th' },
    { value: 15, name: '15th' },
    { value: 16, name: '16th' },
    { value: 18, name: '18th' },
    { value: 19, name: '19th' },
    { value: 20, name: '20th' },
    { value: 21, name: '21st' },
    { value: 22, name: '22nd' },
    { value: 23, name: '23rd' },
    { value: 24, name: '24th' },
    { value: 25, name: '25th' },
    { value: 26, name: '26th' },
    { value: 27, name: '27th' },
    { value: 28, name: '28th' },
    { value: 29, name: '29th' },
    { value: 30, name: '30th' },
    { value: 31, name: '31st' },
]

export const hourOptions = [
    { value: 0, name: '12am' },
    { value: 1, name: '1am' },
    { value: 2, name: '2am' },
    { value: 3, name: '3am' },
    { value: 4, name: '4am' },
    { value: 5, name: '5am' },
    { value: 6, name: '6am' },
    { value: 7, name: '7am' },
    { value: 8, name: '8am' },
    { value: 9, name: '9am' },
    { value: 10, name: '10am' },
    { value: 11, name: '11am' },
    { value: 12, name: '12pm' },
    { value: 13, name: '1pm' },
    { value: 14, name: '2pm' },
    { value: 15, name: '3pm' },
    { value: 16, name: '4pm' },
    { value: 17, name: '5pm' },
    { value: 18, name: '6pm' },
    { value: 19, name: '7pm' },
    { value: 20, name: '8pm' },
    { value: 21, name: '9pm' },
    { value: 22, name: '10pm' },
    { value: 23, name: '11pm' },
]

export const minuteOptions = [
    { value: 0, name: '00' },
    { value: 5, name: '05' },
    { value: 10, name: '10' },
    { value: 15, name: '15' },
    { value: 20, name: '20' },
    { value: 25, name: '25' },
    { value: 30, name: '30' },
    { value: 35, name: '35' },
    { value: 40, name: '40' },
    { value: 45, name: '45' },
    { value: 50, name: '50' },
    { value: 55, name: '55' },
]

export const deviceOptions = [
    { name: 'Screen', value: 'Screen' },
    { name: 'Blackberry PlayBook', value: 'Blackberry PlayBook' },
    { name: 'Blackberry PlayBook landscape', value: 'Blackberry PlayBook landscape' },
    { name: 'BlackBerry Z30', value: 'BlackBerry Z30' },
    { name: 'BlackBerry Z30 landscape', value: 'BlackBerry Z30 landscape' },
    { name: 'Galaxy Note 3', value: 'Galaxy Note 3' },
    { name: 'Galaxy Note 3 landscape', value: 'Galaxy Note 3 landscape' },
    { name: 'Galaxy Note II', value: 'Galaxy Note II' },
    { name: 'Galaxy Note II landscape', value: 'Galaxy Note II landscape' },
    { name: 'Galaxy S III', value: 'Galaxy S III' },
    { name: 'Galaxy S III landscape', value: 'Galaxy S III landscape' },
    { name: 'Galaxy S5', value: 'Galaxy S5' },
    { name: 'Galaxy S5 landscape', value: 'Galaxy S5 landscape' },
    { name: 'iPad', value: 'iPad' },
    { name: 'iPad landscape', value: 'iPad landscape' },
    { name: 'iPad Mini', value: 'iPad Mini' },
    { name: 'iPad Mini landscape', value: 'iPad Mini landscape' },
    { name: 'iPad Pro', value: 'iPad Pro' },
    { name: 'iPad Pro landscape', value: 'iPad Pro landscape' },
    { name: 'iPhone 4', value: 'iPhone 4' },
    { name: 'iPhone 4 landscape', value: 'iPhone 4 landscape' },
    { name: 'iPhone 5', value: 'iPhone 5' },
    { name: 'iPhone 5 landscape', value: 'iPhone 5 landscape' },
    { name: 'iPhone 6', value: 'iPhone 6' },
    { name: 'iPhone 6 landscape', value: 'iPhone 6 landscape' },
    { name: 'iPhone 6 Plus', value: 'iPhone 6 Plus' },
    { name: 'iPhone 6 Plus landscape', value: 'iPhone 6 Plus landscape' },
    { name: 'iPhone 7', value: 'iPhone 7' },
    { name: 'iPhone 7 landscape', value: 'iPhone 7 landscape' },
    { name: 'iPhone 7 Plus', value: 'iPhone 7 Plus' },
    { name: 'iPhone 7 Plus landscape', value: 'iPhone 7 Plus landscape' },
    { name: 'iPhone 8', value: 'iPhone 8' },
    { name: 'iPhone 8 landscape', value: 'iPhone 8 landscape' },
    { name: 'iPhone 8 Plus', value: 'iPhone 8 Plus' },
    { name: 'iPhone 8 Plus landscape', value: 'iPhone 8 Plus landscape' },
    { name: 'iPhone SE', value: 'iPhone SE' },
    { name: 'iPhone SE landscape', value: 'iPhone SE landscape' },
    { name: 'iPhone X', value: 'iPhone X' },
    { name: 'iPhone X landscape', value: 'iPhone X landscape' },
    { name: 'JioPhone 2', value: 'JioPhone 2' },
    { name: 'JioPhone 2 landscape', value: 'JioPhone 2 landscape' },
    { name: 'Kindle Fire HDX', value: 'Kindle Fire HDX' },
    { name: 'Kindle Fire HDX landscape', value: 'Kindle Fire HDX landscape' },
    { name: 'LG Optimus L70', value: 'LG Optimus L70' },
    { name: 'LG Optimus L70 landscape', value: 'LG Optimus L70 landscape' },
    { name: 'Microsoft Lumia 550', value: 'Microsoft Lumia 550' },
    { name: 'Microsoft Lumia 950', value: 'Microsoft Lumia 950' },
    { name: 'Microsoft Lumia 950 landscape', value: 'Microsoft Lumia 950 landscape' },
    { name: 'Nexus 10', value: 'Nexus 10' },
    { name: 'Nexus 10 landscape', value: 'Nexus 10 landscape' },
    { name: 'Nexus 4', value: 'Nexus 4' },
    { name: 'Nexus 4 landscape', value: 'Nexus 4 landscape' },
    { name: 'Nexus 5', value: 'Nexus 5' },
    { name: 'Nexus 5 landscape', value: 'Nexus 5 landscape' },
    { name: 'Nexus 5X', value: 'Nexus 5X' },
    { name: 'Nexus 5X landscape', value: 'Nexus 5X landscape' },
    { name: 'Nexus 6', value: 'Nexus 6' },
    { name: 'Nexus 6 landscape', value: 'Nexus 6 landscape' },
    { name: 'Nexus 6P', value: 'Nexus 6P' },
    { name: 'Nexus 6P landscape', value: 'Nexus 6P landscape' },
    { name: 'Nexus 7', value: 'Nexus 7' },
    { name: 'Nexus 7 landscape', value: 'Nexus 7 landscape' },
    { name: 'Nokia Lumia 520', value: 'Nokia Lumia 520' },
    { name: 'Nokia Lumia 520 landscape', value: 'Nokia Lumia 520 landscape' },
    { name: 'Nokia N9', value: 'Nokia N9' },
    { name: 'Nokia N9 landscape', value: 'Nokia N9 landscape' },
    { name: 'Pixel 2', value: 'Pixel 2' },
    { name: 'Pixel 2 landscape', value: 'Pixel 2 landscape' },
    { name: 'Pixel 2 XL', value: 'Pixel 2 XL' },
    { name: 'Pixel 2 XL landscape', value: 'Pixel 2 XL landscape' },
]
